name: ci cd pipeline with kubernetes
on:
  push:
    branches:
      - main
      - dev

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: run the hello world
        run: echo "Hello world"

      - name: run the date command
        run: date
